"""Built-in node type definitions for all palette items.

These mirror the palette in canvas.py and provide property metadata for the
Object Inspector without requiring a project or custom YAML files.
"""
from __future__ import annotations

from pocketflow_creator.model.node_type import NodeTypeDefinition

# Each entry uses the same property-metadata dict format as custom YAML:
# { "type": str, "default": value, "description": str }

BUILTIN_NODE_TYPES: dict[str, NodeTypeDefinition] = {
    t.node_type_id: t
    for t in [
        NodeTypeDefinition(
            node_type_id="start_node",
            display_name="Start Node",
            category="Flow Control",
            base_class="Node",
            actions=["default"],
            properties={},
        ),
        NodeTypeDefinition(
            node_type_id="stop_node",
            display_name="Stop Node",
            category="Flow Control",
            base_class="Node",
            properties={},
        ),
        NodeTypeDefinition(
            node_type_id="basic_node",
            display_name="Basic Node",
            category="Core",
            base_class="Node",
            actions=["default"],
            properties={},
        ),
        NodeTypeDefinition(
            node_type_id="router_node",
            display_name="Router Node",
            category="Flow Control",
            base_class="Node",
            properties={
                "routes": {
                    "type": "string",
                    "default": "",
                    "description": "Comma-separated action names this router may return",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="llm_prompt_node",
            display_name="LLM Prompt Node",
            category="AI",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "prompt_type": {
                    "type": "string",
                    "default": "string",
                    "choices": ["string", "path"],
                    "description": "'string' = literal prompt text, 'path' = relative path to a Markdown file",
                },
                "prompt_file": {
                    "type": "string",
                    "default": "",
                    "description": "Prompt text (if prompt_type=string) or relative file path (if prompt_type=path)",
                },
                "model": {
                    "type": "string",
                    "default": "",
                    "description": "LLM model name (blank = project default)",
                },
                "temperature": {
                    "type": "number",
                    "default": 0.7,
                    "description": "Sampling temperature 0–1",
                },
                "max_tokens": {
                    "type": "integer",
                    "default": 1024,
                    "description": "Maximum tokens in the response",
                },
                "system_prompt": {
                    "type": "string",
                    "default": "",
                    "description": "Optional system prompt override",
                },
                "input_key": {
                    "type": "string",
                    "default": "input",
                    "description": "Shared store key read by prep()",
                },
                "output_key": {
                    "type": "string",
                    "default": "output",
                    "description": "Shared store key written by post()",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="json_llm_node",
            display_name="JSON LLM Node",
            category="AI",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "prompt_type": {
                    "type": "string",
                    "default": "string",
                    "choices": ["string", "path"],
                    "description": "'string' = literal prompt text, 'path' = relative file path",
                },
                "prompt_file": {
                    "type": "string",
                    "default": "",
                    "description": "Prompt text (if prompt_type=string) or relative file path (if prompt_type=path)",
                },
                "model": {
                    "type": "string",
                    "default": "",
                    "description": "LLM model name",
                },
                "temperature": {
                    "type": "number",
                    "default": 0.2,
                    "description": "Sampling temperature (lower = more deterministic JSON)",
                },
                "output_key": {
                    "type": "string",
                    "default": "result",
                    "description": "Shared store key to write the parsed JSON object to",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="classifier_node",
            display_name="Classifier Node",
            category="AI",
            base_class="Node",
            allow_prompt_files=True,
            properties={
                "prompt_type": {
                    "type": "string",
                    "default": "string",
                    "choices": ["string", "path"],
                    "description": "'string' = literal prompt text, 'path' = relative path to a Markdown file",
                },
                "prompt_file": {
                    "type": "string",
                    "default": "",
                    "description": "Classification prompt. Leave empty to auto-build from categories and input_key.",
                },
                "categories": {
                    "type": "string",
                    "default": "",
                    "description": "Comma-separated category labels — must match the node's Actions field",
                },
                "model": {
                    "type": "string",
                    "default": "",
                    "description": "LLM model name (blank = project default)",
                },
                "input_key": {
                    "type": "string",
                    "default": "input",
                    "description": "Shared store key containing the text to classify",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="python_tool_node",
            display_name="Python Tool Node",
            category="Code",
            base_class="Node",
            actions=["default"],
            properties={
                "tool_name": {
                    "type": "string",
                    "default": "",
                    "description": "Name of the @tool-decorated function to call",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="file_reader_node",
            display_name="File Reader Node",
            category="Data/IO",
            base_class="Node",
            actions=["default"],
            properties={
                "file_path": {
                    "type": "string",
                    "default": "",
                    "description": "Path to file (absolute or relative to project root)",
                },
                "encoding": {
                    "type": "string",
                    "default": "utf-8",
                    "description": "File character encoding",
                },
                "output_key": {
                    "type": "string",
                    "default": "content",
                    "description": "Shared store key to write the file contents to",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="file_writer_node",
            display_name="File Writer Node",
            category="Data/IO",
            base_class="Node",
            actions=["default"],
            properties={
                "file_path": {
                    "type": "string",
                    "default": "",
                    "description": "Path to the file to write",
                },
                "encoding": {
                    "type": "string",
                    "default": "utf-8",
                    "description": "File character encoding",
                },
                "mode": {
                    "type": "string",
                    "default": "write",
                    "description": "'write' to overwrite, 'append' to add to the end",
                },
                "input_key": {
                    "type": "string",
                    "default": "content",
                    "description": "Shared store key whose value is written to the file",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="human_review_node",
            display_name="Human Review Node",
            category="Human-in-the-Loop",
            base_class="Node",
            actions=["approved", "rejected"],
            properties={
                "prompt": {
                    "type": "string",
                    "default": "Please review the following and approve or reject:",
                    "description": "Message shown to the human reviewer",
                },
                "input_key": {
                    "type": "string",
                    "default": "content",
                    "description": "Shared store key whose value is shown for review",
                },
                "feedback_key": {
                    "type": "string",
                    "default": "feedback",
                    "description": "Shared store key to write reviewer feedback to",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="human_input_node",
            display_name="Human Input Node",
            category="Human-in-the-Loop",
            base_class="Node",
            actions=["saved", "cancelled"],
            properties={
                "input_type": {
                    "type": "string",
                    "default": "form",
                    "choices": ["form", "list"],
                    "description": "'form' = collect named fields, 'list' = collect a list of items",
                },
                "title": {
                    "type": "string",
                    "default": "Human Input",
                    "description": "Dialog window title shown to the user",
                },
                "fields": {
                    "type": "string",
                    "default": "",
                    "description": (
                        "Form mode only — semicolon-separated field definitions: "
                        "label:type:default:choices. "
                        "Type: string|integer|float. "
                        "Choices: comma-separated (makes a dropdown). "
                        "Example: Name:string::;Age:integer:18:;Country:string:US:US,UK,CA"
                    ),
                },
                "item_prompt": {
                    "type": "string",
                    "default": "",
                    "description": "List mode only — instruction text shown above the list",
                },
                "item_label": {
                    "type": "string",
                    "default": "item",
                    "description": "List mode only — singular label for each entry (e.g. 'review')",
                },
                "output_key": {
                    "type": "string",
                    "default": "input",
                    "description": (
                        "Shared store key written on Save. "
                        "Form mode: dict of field values. List mode: list of strings."
                    ),
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="batch_node",
            display_name="Batch Node",
            category="Processing",
            base_class="BatchNode",
            actions=["default"],
            properties={
                "input_key": {
                    "type": "string",
                    "default": "items",
                    "description": "Shared store key containing the list to iterate over",
                },
                "output_key": {
                    "type": "string",
                    "default": "results",
                    "description": "Shared store key to write the list of results to",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="async_node",
            display_name="Async Node",
            category="Async",
            base_class="AsyncNode",
            actions=["default"],
            properties={
                "timeout": {
                    "type": "number",
                    "default": 30.0,
                    "description": "Async timeout in seconds",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="async_batch_node",
            display_name="Async Batch Node",
            category="Async",
            base_class="AsyncBatchNode",
            actions=["default"],
            properties={
                "input_key": {
                    "type": "string",
                    "default": "items",
                    "description": "Shared store key containing the list to iterate over",
                },
                "output_key": {
                    "type": "string",
                    "default": "results",
                    "description": "Shared store key to write results to",
                },
                "timeout": {
                    "type": "number",
                    "default": 30.0,
                    "description": "Async timeout per item in seconds",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="async_parallel_batch_node",
            display_name="Async Parallel Batch Node",
            category="Async",
            base_class="AsyncParallelBatchNode",
            actions=["default"],
            properties={
                "input_key": {
                    "type": "string",
                    "default": "items",
                    "description": "Shared store key containing the list to iterate over",
                },
                "output_key": {
                    "type": "string",
                    "default": "results",
                    "description": "Shared store key to write results to",
                },
                "max_workers": {
                    "type": "integer",
                    "default": 4,
                    "description": "Maximum number of concurrent async workers",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="agent_node",
            display_name="Agent Node",
            category="AI",
            base_class="Node",
            actions=["done", "continue"],
            allow_prompt_files=True,
            properties={
                "prompt_type": {
                    "type": "string",
                    "default": "string",
                    "choices": ["string", "path"],
                    "description": "'string' = literal prompt text, 'path' = relative path to a Markdown file",
                },
                "prompt_file": {
                    "type": "string",
                    "default": "",
                    "description": "Agent system/task prompt. Leave empty to use the value at input_key.",
                },
                "max_steps": {
                    "type": "integer",
                    "default": 10,
                    "description": "Maximum number of agent reasoning steps",
                },
                "model": {
                    "type": "string",
                    "default": "",
                    "description": "LLM model name (blank = project default)",
                },
                "input_key": {
                    "type": "string",
                    "default": "task",
                    "description": "Shared store key containing the agent task description",
                },
                "output_key": {
                    "type": "string",
                    "default": "result",
                    "description": "Shared store key to write the final agent output to",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="rag_node",
            display_name="RAG Node",
            category="AI",
            base_class="Node",
            actions=["default"],
            properties={
                "index_path": {
                    "type": "string",
                    "default": "",
                    "description": "Path to the vector index directory",
                },
                "top_k": {
                    "type": "integer",
                    "default": 5,
                    "description": "Number of documents to retrieve",
                },
                "query_key": {
                    "type": "string",
                    "default": "query",
                    "description": "Shared store key containing the search query",
                },
                "output_key": {
                    "type": "string",
                    "default": "context",
                    "description": "Shared store key to write retrieved documents to",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="judge_node",
            display_name="Judge Node",
            category="AI",
            base_class="Node",
            actions=["pass", "fail"],
            allow_prompt_files=True,
            properties={
                "prompt_type": {
                    "type": "string",
                    "default": "string",
                    "choices": ["string", "path"],
                    "description": "'string' = literal prompt text, 'path' = relative path to a Markdown file",
                },
                "prompt_file": {
                    "type": "string",
                    "default": "",
                    "description": "Evaluation prompt template. Leave empty to auto-build from criteria and input_key.",
                },
                "model": {
                    "type": "string",
                    "default": "",
                    "description": "LLM model name (blank = project default)",
                },
                "criteria": {
                    "type": "string",
                    "default": "",
                    "description": "Evaluation criteria used in the auto-built prompt when prompt_file is empty",
                },
                "threshold": {
                    "type": "number",
                    "default": 0.7,
                    "description": "Score threshold (0–1) above which the judgment is 'pass'",
                },
                "input_key": {
                    "type": "string",
                    "default": "content",
                    "description": "Shared store key containing the content to evaluate",
                },
            },
        ),
        NodeTypeDefinition(
            node_type_id="subflow_node",
            display_name="Subflow Node",
            category="Flow Control",
            base_class="Node",
            actions=["default"],
            properties={
                "subflow_ref": {
                    "type": "string",
                    "default": "",
                    "description": "Relative path to the subflow .pfcgraph.yaml file",
                },
            },
        ),
        # ── AI / Reasoning ────────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="chain_of_thought_node",
            display_name="Chain of Thought Node",
            category="AI/Reasoning",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "steps": {"type": "int", "default": 3, "description": "Number of reasoning steps"},
                "output_key": {"type": "string", "default": "cot_result", "description": "Shared-store key for the result"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="majority_vote_node",
            display_name="Majority Vote Node",
            category="AI/Reasoning",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "samples": {"type": "int", "default": 5, "description": "Number of samples to generate"},
                "output_key": {"type": "string", "default": "voted_result", "description": "Shared-store key for the result"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="supervisor_node",
            display_name="Supervisor Node",
            category="AI/Reasoning",
            base_class="Node",
            actions=["continue", "done", "error"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "max_iterations": {"type": "int", "default": 10, "description": "Maximum supervision iterations"},
                "output_key": {"type": "string", "default": "supervisor_result", "description": "Shared-store key for the result"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="debate_advocate_node",
            display_name="Debate Advocate Node",
            category="AI/Reasoning",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "position": {"type": "string", "default": "pro", "description": "Debate position: pro or con"},
                "output_key": {"type": "string", "default": "advocate_argument", "description": "Shared-store key for the argument"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="debate_judge_node",
            display_name="Debate Judge Node",
            category="AI/Reasoning",
            base_class="Node",
            actions=["pro_wins", "con_wins", "tie"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "output_key": {"type": "string", "default": "debate_verdict", "description": "Shared-store key for the verdict"},
            },
        ),
        # ── Web / Search ──────────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="web_search_node",
            display_name="Web Search Node",
            category="Web/Search",
            base_class="Node",
            actions=["default", "no_results"],
            properties={
                "engine": {"type": "string", "default": "duckduckgo", "description": "Search engine: duckduckgo, google, bing"},
                "num_results": {"type": "int", "default": 5, "description": "Number of results to return"},
                "query_key": {"type": "string", "default": "search_query", "description": "Shared-store key containing the query"},
                "output_key": {"type": "string", "default": "search_results", "description": "Shared-store key for results"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="web_scrape_node",
            display_name="Web Scrape Node",
            category="Web/Search",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "url_key": {"type": "string", "default": "url", "description": "Shared-store key containing the URL"},
                "output_key": {"type": "string", "default": "scraped_text", "description": "Shared-store key for scraped content"},
                "timeout": {"type": "int", "default": 10, "description": "HTTP timeout in seconds"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="api_call_node",
            display_name="API Call Node",
            category="Web/Search",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "url": {"type": "string", "default": "", "description": "Endpoint URL (may contain {{key}} interpolations)"},
                "method": {"type": "string", "default": "GET", "description": "HTTP method: GET, POST, PUT, DELETE"},
                "headers_key": {"type": "string", "default": "", "description": "Shared-store key for extra headers dict"},
                "body_key": {"type": "string", "default": "", "description": "Shared-store key for request body"},
                "output_key": {"type": "string", "default": "api_response", "description": "Shared-store key for the response"},
            },
        ),
        # ── Data / Vector / Embeddings ────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="text_chunk_node",
            display_name="Text Chunk Node",
            category="Data/Vector",
            base_class="Node",
            actions=["default"],
            properties={
                "input_key": {"type": "string", "default": "text", "description": "Shared-store key containing source text"},
                "chunk_size": {"type": "int", "default": 512, "description": "Chunk size in tokens/characters"},
                "overlap": {"type": "int", "default": 64, "description": "Overlap between consecutive chunks"},
                "output_key": {"type": "string", "default": "chunks", "description": "Shared-store key for the chunks list"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="embed_node",
            display_name="Embed Node",
            category="Data/Vector",
            base_class="Node",
            actions=["default"],
            properties={
                "model": {"type": "string", "default": "text-embedding-3-small", "description": "Embedding model name"},
                "input_key": {"type": "string", "default": "chunks", "description": "Shared-store key containing text or list of texts"},
                "output_key": {"type": "string", "default": "embeddings", "description": "Shared-store key for the embedding vectors"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="vector_index_node",
            display_name="Vector Index Node",
            category="Data/Vector",
            base_class="Node",
            actions=["default"],
            properties={
                "store_type": {"type": "string", "default": "faiss", "description": "Vector store backend: faiss, chroma, pinecone"},
                "embeddings_key": {"type": "string", "default": "embeddings", "description": "Shared-store key for vectors to index"},
                "index_key": {"type": "string", "default": "vector_index", "description": "Shared-store key for the built index"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="vector_retrieve_node",
            display_name="Vector Retrieve Node",
            category="Data/Vector",
            base_class="Node",
            actions=["default", "no_results"],
            properties={
                "index_key": {"type": "string", "default": "vector_index", "description": "Shared-store key for the index"},
                "query_key": {"type": "string", "default": "query", "description": "Shared-store key for the query text or vector"},
                "top_k": {"type": "int", "default": 5, "description": "Number of nearest neighbours to return"},
                "output_key": {"type": "string", "default": "retrieved_docs", "description": "Shared-store key for results"},
            },
        ),
        # ── Database / SQL ────────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="db_schema_node",
            display_name="DB Schema Node",
            category="Database/SQL",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "connection_key": {"type": "string", "default": "db_conn", "description": "Shared-store key for the DB connection string"},
                "output_key": {"type": "string", "default": "db_schema", "description": "Shared-store key for the schema description"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="nl_to_sql_node",
            display_name="NL to SQL Node",
            category="Database/SQL",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "schema_key": {"type": "string", "default": "db_schema", "description": "Shared-store key for schema context"},
                "question_key": {"type": "string", "default": "nl_question", "description": "Shared-store key for natural-language query"},
                "output_key": {"type": "string", "default": "sql_query", "description": "Shared-store key for the generated SQL"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="sql_execute_node",
            display_name="SQL Execute Node",
            category="Database/SQL",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "connection_key": {"type": "string", "default": "db_conn", "description": "Shared-store key for the DB connection string"},
                "sql_key": {"type": "string", "default": "sql_query", "description": "Shared-store key containing the SQL to execute"},
                "output_key": {"type": "string", "default": "query_results", "description": "Shared-store key for results"},
            },
        ),
        # ── Voice / Audio ─────────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="speech_to_text_node",
            display_name="Speech to Text Node",
            category="Voice/Audio",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "model": {"type": "string", "default": "whisper-1", "description": "ASR model name"},
                "audio_key": {"type": "string", "default": "audio_path", "description": "Shared-store key for audio file path"},
                "output_key": {"type": "string", "default": "transcript", "description": "Shared-store key for the transcript"},
                "language": {"type": "string", "default": "", "description": "ISO language code (empty = auto-detect)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="text_to_speech_node",
            display_name="Text to Speech Node",
            category="Voice/Audio",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "model": {"type": "string", "default": "tts-1", "description": "TTS model name"},
                "voice": {"type": "string", "default": "alloy", "description": "Voice identifier"},
                "text_key": {"type": "string", "default": "tts_text", "description": "Shared-store key for input text"},
                "output_key": {"type": "string", "default": "audio_path", "description": "Shared-store key for output audio path"},
            },
        ),
        # ── Document / Vision ─────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="pdf_extract_node",
            display_name="PDF Extract Node",
            category="Document/Vision",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "pdf_key": {"type": "string", "default": "pdf_path", "description": "Shared-store key for the PDF file path"},
                "output_key": {"type": "string", "default": "pdf_text", "description": "Shared-store key for extracted text"},
                "pages": {"type": "string", "default": "", "description": "Page range, e.g. '1-5' (empty = all)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="image_vision_node",
            display_name="Image Vision Node",
            category="Document/Vision",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "Vision-capable model name"},
                "image_key": {"type": "string", "default": "image_path", "description": "Shared-store key for image path or URL"},
                "output_key": {"type": "string", "default": "vision_result", "description": "Shared-store key for the description/analysis"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="data_validate_node",
            display_name="Data Validate Node",
            category="Document/Vision",
            base_class="Node",
            actions=["valid", "invalid"],
            properties={
                "input_key": {"type": "string", "default": "data", "description": "Shared-store key for data to validate"},
                "schema_key": {"type": "string", "default": "validation_schema", "description": "Shared-store key for JSON Schema"},
                "errors_key": {"type": "string", "default": "validation_errors", "description": "Shared-store key for validation error list"},
            },
        ),
        # ── Code / Execution ──────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="code_gen_node",
            display_name="Code Gen Node",
            category="Code/Execution",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "language": {"type": "string", "default": "python", "description": "Target programming language"},
                "spec_key": {"type": "string", "default": "code_spec", "description": "Shared-store key for the code specification"},
                "output_key": {"type": "string", "default": "generated_code", "description": "Shared-store key for the generated code"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="code_exec_node",
            display_name="Code Exec Node",
            category="Code/Execution",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "code_key": {"type": "string", "default": "generated_code", "description": "Shared-store key containing code to execute"},
                "sandbox": {"type": "bool", "default": True, "description": "Run in restricted sandbox"},
                "timeout": {"type": "int", "default": 30, "description": "Execution timeout in seconds"},
                "output_key": {"type": "string", "default": "exec_output", "description": "Shared-store key for stdout/result"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="test_gen_node",
            display_name="Test Gen Node",
            category="Code/Execution",
            base_class="Node",
            actions=["default"],
            allow_prompt_files=True,
            properties={
                "model": {"type": "string", "default": "gpt-4o", "description": "LLM model name"},
                "code_key": {"type": "string", "default": "generated_code", "description": "Shared-store key for source code"},
                "output_key": {"type": "string", "default": "test_code", "description": "Shared-store key for generated test code"},
                "framework": {"type": "string", "default": "pytest", "description": "Test framework: pytest, unittest"},
            },
        ),
        # ── Data Processing ───────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="map_node",
            display_name="Map Node",
            category="Data Processing",
            base_class="Node",
            actions=["default"],
            properties={
                "input_key": {"type": "string", "default": "items", "description": "Shared-store key for the input list"},
                "output_key": {"type": "string", "default": "mapped_items", "description": "Shared-store key for the output list"},
                "transform": {"type": "string", "default": "", "description": "Python expression applied to each item (item variable)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="reduce_node",
            display_name="Reduce Node",
            category="Data Processing",
            base_class="Node",
            actions=["default"],
            properties={
                "input_key": {"type": "string", "default": "mapped_items", "description": "Shared-store key for the input list"},
                "output_key": {"type": "string", "default": "reduced_result", "description": "Shared-store key for the reduced value"},
                "reducer": {"type": "string", "default": "sum", "description": "Reduction function: sum, concat, max, min, or Python expression"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="condition_node",
            display_name="Condition Node",
            category="Data Processing",
            base_class="Node",
            actions=["true", "false"],
            properties={
                "expression": {"type": "string", "default": "", "description": "Python expression to evaluate (accesses shared store as 'store')"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="loop_counter_node",
            display_name="Loop Counter Node",
            category="Data Processing",
            base_class="Node",
            actions=["continue", "done"],
            properties={
                "max_iterations": {"type": "int", "default": 10, "description": "Maximum loop iterations"},
                "counter_key": {"type": "string", "default": "loop_count", "description": "Shared-store key for the iteration counter"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="transform_node",
            display_name="Transform Node",
            category="Data Processing",
            base_class="Node",
            actions=["default"],
            properties={
                "input_key": {"type": "string", "default": "data", "description": "Shared-store key for input data"},
                "output_key": {"type": "string", "default": "transformed_data", "description": "Shared-store key for output data"},
                "template": {"type": "string", "default": "", "description": "Jinja2 template or Python expression for transformation"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="merge_node",
            display_name="Merge Node",
            category="Data Processing",
            base_class="Node",
            actions=["default"],
            properties={
                "input_keys": {"type": "string", "default": "", "description": "Comma-separated list of shared-store keys to merge"},
                "output_key": {"type": "string", "default": "merged_data", "description": "Shared-store key for merged result"},
                "strategy": {"type": "string", "default": "dict_update", "description": "Merge strategy: dict_update, list_concat, string_join"},
            },
        ),
        # ── Calendar ──────────────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="calendar_read_node",
            display_name="Calendar Read Node",
            category="Calendar",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "calendar_id": {"type": "string", "default": "primary", "description": "Calendar ID or 'primary'"},
                "time_range_key": {"type": "string", "default": "time_range", "description": "Shared-store key for time range dict (start/end)"},
                "output_key": {"type": "string", "default": "calendar_events", "description": "Shared-store key for retrieved events"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="calendar_write_node",
            display_name="Calendar Write Node",
            category="Calendar",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "calendar_id": {"type": "string", "default": "primary", "description": "Calendar ID or 'primary'"},
                "event_key": {"type": "string", "default": "new_event", "description": "Shared-store key for event data dict"},
                "output_key": {"type": "string", "default": "created_event_id", "description": "Shared-store key for the created event ID"},
            },
        ),
        # ── MCP / Agent Protocol ──────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="mcp_tool_node",
            display_name="MCP Tool Node",
            category="MCP/Agent Protocol",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "server_url": {"type": "string", "default": "", "description": "MCP server URL"},
                "tool_name": {"type": "string", "default": "", "description": "Tool name to invoke on the MCP server"},
                "args_key": {"type": "string", "default": "tool_args", "description": "Shared-store key for tool arguments dict"},
                "output_key": {"type": "string", "default": "tool_result", "description": "Shared-store key for the tool result"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="a2a_send_node",
            display_name="A2A Send Node",
            category="MCP/Agent Protocol",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "target_agent_url": {"type": "string", "default": "", "description": "Target agent A2A endpoint URL"},
                "message_key": {"type": "string", "default": "outgoing_message", "description": "Shared-store key for the message to send"},
                "output_key": {"type": "string", "default": "send_response", "description": "Shared-store key for the send acknowledgement"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="a2a_receive_node",
            display_name="A2A Receive Node",
            category="MCP/Agent Protocol",
            base_class="Node",
            actions=["default", "timeout"],
            properties={
                "listen_key": {"type": "string", "default": "a2a_inbox", "description": "Shared-store key where incoming A2A messages are placed"},
                "timeout": {"type": "int", "default": 30, "description": "Wait timeout in seconds"},
                "output_key": {"type": "string", "default": "received_message", "description": "Shared-store key for the received message"},
            },
        ),
        # ── Observability / Utility ───────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="log_node",
            display_name="Log Node",
            category="Observability/Utility",
            base_class="Node",
            actions=["default"],
            properties={
                "message_template": {"type": "string", "default": "", "description": "Log message template ({{key}} interpolation supported)"},
                "level": {"type": "string", "default": "INFO", "description": "Log level: DEBUG, INFO, WARNING, ERROR"},
                "keys_to_log": {"type": "string", "default": "", "description": "Comma-separated shared-store keys to include in the log entry"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="timer_node",
            display_name="Timer Node",
            category="Observability/Utility",
            base_class="Node",
            actions=["default"],
            properties={
                "label": {"type": "string", "default": "timer", "description": "Label for the timing measurement"},
                "mode": {"type": "string", "default": "start", "description": "Operation: start or stop"},
                "output_key": {"type": "string", "default": "elapsed_ms", "description": "Shared-store key for elapsed milliseconds (stop mode)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="cache_node",
            display_name="Cache Node",
            category="Observability/Utility",
            base_class="Node",
            actions=["hit", "miss"],
            properties={
                "cache_key_template": {"type": "string", "default": "", "description": "Template for the cache key ({{store_key}} interpolation)"},
                "value_key": {"type": "string", "default": "cache_value", "description": "Shared-store key for the cached/to-cache value"},
                "ttl": {"type": "int", "default": 300, "description": "Cache TTL in seconds (0 = no expiry)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="trace_node",
            display_name="Trace Node",
            category="Observability/Utility",
            base_class="Node",
            actions=["default"],
            properties={
                "span_name": {"type": "string", "default": "", "description": "OpenTelemetry span name"},
                "keys_to_trace": {"type": "string", "default": "", "description": "Comma-separated shared-store keys to attach as span attributes"},
            },
        ),
        # ── Data Structures / Memory ──────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="registry_node",
            display_name="Registry Node",
            category="Data Structures/Memory",
            base_class="Node",
            actions=["found", "not_found"],
            properties={
                "operation": {"type": "string", "default": "get", "description": "Operation: get, set, delete, list"},
                "registry_key": {"type": "string", "default": "registry", "description": "Shared-store key for the registry dict"},
                "entry_name": {"type": "string", "default": "", "description": "Registry entry name to get/set/delete"},
                "value_key": {"type": "string", "default": "registry_value", "description": "Shared-store key for the value to set or retrieved"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="stack_push_node",
            display_name="Stack Push Node",
            category="Data Structures/Memory",
            base_class="Node",
            actions=["default"],
            properties={
                "stack_key": {"type": "string", "default": "stack", "description": "Shared-store key for the stack list"},
                "value_key": {"type": "string", "default": "push_value", "description": "Shared-store key for the value to push"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="stack_pop_node",
            display_name="Stack Pop Node",
            category="Data Structures/Memory",
            base_class="Node",
            actions=["default", "empty"],
            properties={
                "stack_key": {"type": "string", "default": "stack", "description": "Shared-store key for the stack list"},
                "output_key": {"type": "string", "default": "popped_value", "description": "Shared-store key for the popped value"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="queue_enqueue_node",
            display_name="Queue Enqueue Node",
            category="Data Structures/Memory",
            base_class="Node",
            actions=["default"],
            properties={
                "queue_key": {"type": "string", "default": "queue", "description": "Shared-store key for the queue list"},
                "value_key": {"type": "string", "default": "enqueue_value", "description": "Shared-store key for the value to enqueue"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="queue_dequeue_node",
            display_name="Queue Dequeue Node",
            category="Data Structures/Memory",
            base_class="Node",
            actions=["default", "empty"],
            properties={
                "queue_key": {"type": "string", "default": "queue", "description": "Shared-store key for the queue list"},
                "output_key": {"type": "string", "default": "dequeued_value", "description": "Shared-store key for the dequeued value"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="local_memory_node",
            display_name="Local Memory Node",
            category="Data Structures/Memory",
            base_class="Node",
            actions=["default"],
            properties={
                "operation": {"type": "string", "default": "store", "description": "Operation: store, recall, clear"},
                "memory_key": {"type": "string", "default": "local_memory", "description": "Shared-store key for the memory dict"},
                "slot": {"type": "string", "default": "", "description": "Memory slot name"},
                "value_key": {"type": "string", "default": "memory_value", "description": "Shared-store key for value to store or retrieved"},
            },
        ),
        # ── System / Shell / Hardware ─────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="shell_command_node",
            display_name="Shell Command Node",
            category="System/Shell",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "shell": {"type": "string", "default": "auto", "description": "Shell interpreter: auto, bash, sh, zsh, powershell, cmd"},
                "command_key": {"type": "string", "default": "command", "description": "Shared-store key for the command string to execute"},
                "timeout": {"type": "int", "default": 30, "description": "Execution timeout in seconds"},
                "stdout_key": {"type": "string", "default": "stdout", "description": "Shared-store key for captured stdout"},
                "stderr_key": {"type": "string", "default": "stderr", "description": "Shared-store key for captured stderr"},
                "env_key": {"type": "string", "default": "", "description": "Shared-store key for extra environment variables dict"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="tty_serial_node",
            display_name="TTY Serial Node",
            category="System/Shell",
            base_class="Node",
            actions=["default", "timeout", "error"],
            properties={
                "operation": {"type": "string", "default": "readline", "description": "Operation: open, close, read, readline, write"},
                "port_key": {"type": "string", "default": "serial_port", "description": "Shared-store key for port path (/dev/ttyUSB0, COM3, /dev/tty.usbmodem1)"},
                "baud_rate": {"type": "int", "default": 9600, "description": "Serial baud rate"},
                "timeout": {"type": "float", "default": 1.0, "description": "Read timeout in seconds (0 = non-blocking)"},
                "encoding": {"type": "string", "default": "utf-8", "description": "Decode encoding: utf-8, ascii, bytes (raw bytearray)"},
                "data_key": {"type": "string", "default": "serial_data", "description": "Shared-store key for data to write (write operation)"},
                "output_key": {"type": "string", "default": "serial_read", "description": "Shared-store key for received data (read/readline)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="spreadsheet_node",
            display_name="Spreadsheet Node",
            category="System/Shell",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "operation": {"type": "string", "default": "read", "description": "Operation: read, write, append"},
                "file_key": {"type": "string", "default": "file_path", "description": "Shared-store key for the file path"},
                "format": {"type": "string", "default": "auto", "description": "Format: auto (from extension), csv, tsv, excel"},
                "delimiter": {"type": "string", "default": ",", "description": "Field delimiter (CSV/TSV only; ignored for Excel)"},
                "quoting": {"type": "string", "default": "minimal", "description": "Quoting: minimal, all, non_numeric, none"},
                "sheet_name": {"type": "string", "default": "Sheet1", "description": "Excel sheet name (Excel only)"},
                "has_header": {"type": "bool", "default": True, "description": "Treat first row as column headers"},
                "encoding": {"type": "string", "default": "utf-8", "description": "File encoding (CSV/TSV only)"},
                "data_key": {"type": "string", "default": "table_data", "description": "Shared-store key for data to write"},
                "output_key": {"type": "string", "default": "table_data", "description": "Shared-store key for read data"},
            },
        ),
        # ── Networking / Sockets ──────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="socket_node",
            display_name="Socket Node",
            category="Networking",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "operation": {"type": "string", "default": "connect", "description": "Operation: connect, send, receive, close"},
                "host_key": {"type": "string", "default": "socket_host", "description": "Shared-store key for hostname or IP"},
                "port_key": {"type": "string", "default": "socket_port", "description": "Shared-store key for port number"},
                "proto": {"type": "string", "default": "tcp", "description": "Protocol: tcp or udp"},
                "socket_key": {"type": "string", "default": "socket", "description": "Shared-store key holding the socket object"},
                "data_key": {"type": "string", "default": "socket_data", "description": "Shared-store key for data to send"},
                "output_key": {"type": "string", "default": "socket_recv", "description": "Shared-store key for received data"},
                "timeout": {"type": "float", "default": 5.0, "description": "Operation timeout in seconds"},
                "buffer_size": {"type": "int", "default": 4096, "description": "Receive buffer size in bytes"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="websocket_node",
            display_name="WebSocket Node",
            category="Networking",
            base_class="AsyncNode",
            actions=["default", "closed", "error"],
            properties={
                "operation": {"type": "string", "default": "connect", "description": "Operation: connect, send, receive, close"},
                "url_key": {"type": "string", "default": "ws_url", "description": "Shared-store key for the WebSocket URL (ws:// or wss://)"},
                "ws_key": {"type": "string", "default": "ws_conn", "description": "Shared-store key holding the WebSocket connection object"},
                "data_key": {"type": "string", "default": "ws_send", "description": "Shared-store key for message to send"},
                "output_key": {"type": "string", "default": "ws_recv", "description": "Shared-store key for received message"},
                "timeout": {"type": "float", "default": 10.0, "description": "Receive timeout in seconds"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="webhook_trigger_node",
            display_name="Webhook Trigger Node",
            category="Networking",
            base_class="Node",
            actions=["triggered", "timeout"],
            properties={
                "port": {"type": "int", "default": 8080, "description": "HTTP port to listen on"},
                "path": {"type": "string", "default": "/webhook", "description": "URL path to listen on"},
                "timeout": {"type": "int", "default": 60, "description": "Maximum seconds to wait for a POST request"},
                "output_key": {"type": "string", "default": "webhook_payload", "description": "Shared-store key for the received request body"},
                "headers_key": {"type": "string", "default": "webhook_headers", "description": "Shared-store key for the received request headers"},
            },
        ),
        # ── AI / LLM Utilities ────────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="context_compact_node",
            display_name="Context Compact Node",
            category="AI/LLM Utilities",
            base_class="Node",
            actions=["default"],
            properties={
                "strategy": {"type": "string", "default": "sliding_window", "description": "Strategy: truncate, sliding_window, summarize, extractive, semantic_dedup"},
                "input_key": {"type": "string", "default": "messages", "description": "Shared-store key for messages list or text to compact"},
                "output_key": {"type": "string", "default": "messages", "description": "Shared-store key to write the compacted result"},
                "max_tokens": {"type": "int", "default": 2000, "description": "Target maximum tokens after compaction"},
                "model": {"type": "string", "default": "", "description": "LLM model for summarize strategy (empty = project default)"},
                "similarity_threshold": {"type": "float", "default": 0.92, "description": "Cosine similarity threshold for semantic_dedup"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="conversation_history_node",
            display_name="Conversation History Node",
            category="AI/LLM Utilities",
            base_class="Node",
            actions=["default"],
            properties={
                "operation": {"type": "string", "default": "append", "description": "Operation: append, trim, clear, format"},
                "history_key": {"type": "string", "default": "messages", "description": "Shared-store key for the message list"},
                "role": {"type": "string", "default": "user", "description": "Role for append: user, assistant, system"},
                "content_key": {"type": "string", "default": "content", "description": "Shared-store key for the message content to append"},
                "max_messages": {"type": "int", "default": 20, "description": "Maximum messages to keep on trim"},
                "output_key": {"type": "string", "default": "chat_str", "description": "Shared-store key for formatted string output (format operation)"},
            },
        ),
        # ── Text / Data Processing ────────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="regex_node",
            display_name="Regex Node",
            category="Text/Data Processing",
            base_class="Node",
            actions=["matched", "no_match", "default"],
            properties={
                "operation": {"type": "string", "default": "findall", "description": "Operation: match, search, findall, replace, split"},
                "pattern": {"type": "string", "default": "", "description": "Regular expression pattern string"},
                "flags": {"type": "string", "default": "", "description": "Regex flags: i (ignore case), m (multiline), s (dot-all)"},
                "input_key": {"type": "string", "default": "text", "description": "Shared-store key for the input string"},
                "replacement": {"type": "string", "default": "", "description": "Replacement string for replace operation (supports \\1 groups)"},
                "output_key": {"type": "string", "default": "regex_result", "description": "Shared-store key for the result"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="template_render_node",
            display_name="Template Render Node",
            category="Text/Data Processing",
            base_class="Node",
            actions=["default"],
            properties={
                "template_type": {"type": "string", "default": "string", "description": "Template source: string (inline) or path (file)"},
                "template": {"type": "string", "default": "", "description": "Inline Jinja2 template or path to .j2/.md file"},
                "output_key": {"type": "string", "default": "rendered", "description": "Shared-store key to write the rendered string"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="json_parse_node",
            display_name="JSON Parse Node",
            category="Text/Data Processing",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "operation": {"type": "string", "default": "parse", "description": "Operation: parse (string→dict) or serialize (dict→string)"},
                "input_key": {"type": "string", "default": "json_str", "description": "Shared-store key for JSON string (parse) or object (serialize)"},
                "output_key": {"type": "string", "default": "json_obj", "description": "Shared-store key for the result"},
                "indent": {"type": "int", "default": 0, "description": "JSON indentation for serialize (0 = compact)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="list_ops_node",
            display_name="List Operations Node",
            category="Text/Data Processing",
            base_class="Node",
            actions=["default", "empty"],
            properties={
                "operation": {"type": "string", "default": "filter", "description": "Operation: filter, sort, slice, unique, flatten, reverse, count"},
                "input_key": {"type": "string", "default": "items", "description": "Shared-store key for the input list"},
                "output_key": {"type": "string", "default": "items", "description": "Shared-store key for the result"},
                "expression": {"type": "string", "default": "", "description": "Python expression for filter/sort (item variable)"},
                "start": {"type": "int", "default": 0, "description": "Start index for slice"},
                "stop": {"type": "int", "default": -1, "description": "Stop index for slice (-1 = end)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="string_ops_node",
            display_name="String Operations Node",
            category="Text/Data Processing",
            base_class="Node",
            actions=["default"],
            properties={
                "operation": {"type": "string", "default": "strip", "description": "Operation: split, join, strip, upper, lower, replace, format, truncate"},
                "input_key": {"type": "string", "default": "text", "description": "Shared-store key for the input string (or list for join)"},
                "output_key": {"type": "string", "default": "text", "description": "Shared-store key for the result"},
                "separator": {"type": "string", "default": " ", "description": "Separator for split and join"},
                "find": {"type": "string", "default": "", "description": "Find string for replace"},
                "replacement": {"type": "string", "default": "", "description": "Replacement string for replace"},
                "max_length": {"type": "int", "default": 200, "description": "Maximum length for truncate"},
                "template": {"type": "string", "default": "", "description": "Format template string ({key} placeholders)"},
            },
        ),
        # ── Resilience / Flow Utilities ───────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="retry_node",
            display_name="Retry Node",
            category="Resilience",
            base_class="Node",
            actions=["retry", "done", "give_up"],
            properties={
                "max_attempts": {"type": "int", "default": 3, "description": "Maximum retry attempts before routing give_up"},
                "backoff_base": {"type": "float", "default": 1.0, "description": "Base delay in seconds (doubles each retry)"},
                "jitter": {"type": "bool", "default": True, "description": "Add random jitter to backoff delay"},
                "attempt_key": {"type": "string", "default": "retry_attempt", "description": "Shared-store key for the current attempt counter"},
                "status_key": {"type": "string", "default": "retry_status", "description": "Shared-store key read to determine retry vs done (ok = done)"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="rate_limiter_node",
            display_name="Rate Limiter Node",
            category="Resilience",
            base_class="Node",
            actions=["default"],
            properties={
                "calls_per_min": {"type": "int", "default": 60, "description": "Maximum calls allowed per minute"},
                "timestamp_key": {"type": "string", "default": "last_call_time", "description": "Shared-store key for the last-call Unix timestamp"},
                "label": {"type": "string", "default": "default", "description": "Rate limiter label (allows multiple independent limiters)"},
            },
        ),
        # ── Messaging / Notifications ─────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="email_send_node",
            display_name="Email Send Node",
            category="Messaging",
            base_class="Node",
            actions=["sent", "error"],
            properties={
                "provider": {"type": "string", "default": "smtp", "description": "Email provider: smtp, sendgrid, mailgun"},
                "to_key": {"type": "string", "default": "email_to", "description": "Shared-store key for recipient address(es)"},
                "subject_key": {"type": "string", "default": "email_subject", "description": "Shared-store key for the email subject"},
                "body_key": {"type": "string", "default": "email_body", "description": "Shared-store key for the email body (plain text or HTML)"},
                "html": {"type": "bool", "default": False, "description": "Treat body as HTML"},
                "output_key": {"type": "string", "default": "email_result", "description": "Shared-store key for send result / message ID"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="email_read_node",
            display_name="Email Read Node",
            category="Messaging",
            base_class="Node",
            actions=["default", "no_mail"],
            properties={
                "provider": {"type": "string", "default": "imap", "description": "Mail provider: imap, gmail"},
                "folder": {"type": "string", "default": "INBOX", "description": "Mailbox folder to check"},
                "max_messages": {"type": "int", "default": 10, "description": "Maximum messages to fetch"},
                "unread_only": {"type": "bool", "default": True, "description": "Fetch only unread messages"},
                "output_key": {"type": "string", "default": "emails", "description": "Shared-store key for the list of message dicts"},
            },
        ),
        NodeTypeDefinition(
            node_type_id="notification_node",
            display_name="Notification Node",
            category="Messaging",
            base_class="Node",
            actions=["default", "error"],
            properties={
                "channel": {"type": "string", "default": "slack", "description": "Platform: slack, discord, teams, telegram"},
                "webhook_url_key": {"type": "string", "default": "webhook_url", "description": "Shared-store key for the platform webhook URL"},
                "message_key": {"type": "string", "default": "notification", "description": "Shared-store key for the message text"},
                "title": {"type": "string", "default": "", "description": "Optional title / header for rich message formats"},
            },
        ),
        # ── Security / Configuration ──────────────────────────────────────────
        NodeTypeDefinition(
            node_type_id="secret_node",
            display_name="Secret Node",
            category="Security",
            base_class="Node",
            actions=["default", "not_found"],
            properties={
                "source": {"type": "string", "default": "env", "description": "Secret source: env, dotenv, aws_secrets, vault"},
                "secret_name": {"type": "string", "default": "", "description": "Environment variable name or secret path/name"},
                "output_key": {"type": "string", "default": "secret", "description": "Shared-store key to write the retrieved secret value"},
                "required": {"type": "bool", "default": True, "description": "If true, route not_found when secret is missing"},
            },
        ),
    ]
}
